apiVersion: apps/v1
kind: Deployment
metadata:
  name: trident-server-deployment
  namespace: trident
  labels:
    app: trident-server
spec: 
  replicas: 3
  selector:
    matchLabels: 
      app: trident-server
  template:
    metadata:
      labels:
        app: trident-server
    spec:
      containers:
        - name: trident-server
          image: ghcr.io/epyklab/trident-server:latest
          ports:
            - containerPort: 5555
      # imagePullSecrets:
      #   - name: ghcr-secret
