name: Build server container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-server-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './server'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'build server image'
            run: |
              docker build . --tag ghcr.io/epyklab/trident-server:latest
              docker push ghcr.io/epyklab/trident-server:latest

